### ISSUE TITLE
兄弟动态添加子元素，页面刷新的不正确，会错 。

### ISSUE THREAD

**Issue by zjmccc** [haishangfeie/path-view-component#1]

**Comment by haishangfeie** [comment]
你好，请问是怎样刷新不正确？会报错？

**Comment by zjmccc** [comment]
动态的添加子元素，地址栏会回到第一栏，但是以前的也还在，而且元素栏也不对。

**Comment by haishangfeie** [comment]
你好，现在更新视图时视图会刷新回到第一栏，地址也会重置。

**Comment by zjmccc** [comment]
OK 谢谢大佬，要不给个类型方式。

**Comment by haishangfeie** [comment]
类型方式？

**Comment by zjmccc** [comment]
QQ wehchar 都可以。或者你指定一个都可以。

**Comment by haishangfeie** [comment]
这个就算了吧，你在博客和github留言都可以的，以后我也会尽可能每天查看信息的

**Comment by zjmccc** [comment]
你这刷新不解决根本问题啊。增加后就刷新整个组件。客户又去一个一个的找。太麻烦了。你没改的时候我就是直接页面结构上传到服务器然后刷新整个页面重新拉取和你现在的体验差不多。能不能添加以后不乱？

**Comment by haishangfeie** [comment]
嗯嗯，这个应该是可以做到，下班后我抽时间想想。

**Comment by zjmccc** [comment]
谢谢大佬。写好了麻烦联系一下。现在这个客户体验有点差。

**Comment by haishangfeie** [comment]
好

**Comment by haishangfeie** [comment]
你好，可以描述一下你使用的场景吗

**Comment by zjmccc** [comment]
比如现在有很多种食物。蔬菜 水果 水果下面有苹果 苹果下面有富士山苹果 富士山苹果下面有青苹果，红苹果，这是给用户自定义的，所以添加的时候不能让添加一个就让客户回到第一层把。
那个点击添加子元素的算法我 已经写好了

**Comment by haishangfeie** [comment]
已更新代码，你可以试着开启位置保持,keepLoc="{{true}}"

**Comment by zjmccc** [comment]
老哥新的问题出现了。ios不兼容了。
都显示不出来了。
