### ISSUE TITLE
你好，我用你给的非树形结构的值传入进去，显示不正确，所有值全部显示在了第一级

### ISSUE THREAD

**Issue by sk872529557** [haishangfeie/path-view-component#3]

**Comment by haishangfeie** [comment]
抱歉，现在才看到。

**Comment by sk872529557** [comment]
没事，谢谢你的解答------------------ 原始邮件 ------------------
发件人: "haishangfeie"<notifications@github.com>
发送时间: 2019年10月30日(星期三) 中午1:25
收件人: "haishangfeie/path-view-component"<path-view-component@noreply.github.com>;
抄送: "sk872529557"<872529557@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [haishangfeie/path-view-component] 你好，我用你给的非树形结构的值传入进去，显示不正确，所有值全部显示在了第一级 (#3)



抱歉，现在才看到。
 
&mdash;
